{% set version = "0.3.2" %}

package:
  name: openblas
  version: {{ version }}

source:
  fn: openblas-{{ version }}.tar.gz
  url: https://github.com/xianyi/OpenBLAS/archive/v{{ version }}.tar.gz
  sha256: e8ba64f6b103c511ae13736100347deb7121ba9b41ba82052b1a018a65c0cb15

build:
  number: 0
  skip: true  # [win and vc!=14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}  # [unix]
    - perl
    - flang                      # [win]
    - cmake                      # [win]
    - curl                       # [win]
    - jom                        # [win]

  host:
    - libflang                   # [win]
    - libgfortran-ng >=3.0       # [osx]
    - libgfortran-ng >=4.9       # [linux]

  run:
    - libflang                   # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libopenblas.a                            # [unix]
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${SHLIB_EXT}']"  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\openblas.lib exit 1    # [win]

about:
  home: http://www.openblas.net/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version.

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - jschueller
    - isuruf
