{% set version = "0.3.5" %}

package:
  name: openblas
  version: {{ version }}

source:
  fn: openblas-{{ version }}.tar.gz
  url: https://github.com/xianyi/OpenBLAS/archive/v{{ version }}.tar.gz
  sha256: 0950c14bd77c90a6427e26210d6dab422271bc86f9fc69126725833ecdaa0e85
  patches:
    - 0002-Fix-gfortran-detection-for-ctng-based-cross-compilers.patch    # [c_compiler == 'gcc']

build:
  number: 1000
  skip: true  # [win and vc!=14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - perl
    - cmake                      # [win]
    - curl                       # [win]
    - jom                        # [win]
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libopenblas.a                            # [unix]
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${SHLIB_EXT}']"  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\openblas.lib exit 1    # [win]

about:
  home: http://www.openblas.net/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version.

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - jschueller
    - isuruf
