{% set version = "0.2.20" %}

package:
  name: openblas
  version: {{ version }}

source:
  fn: openblas-{{ version }}.tar.gz
  url: https://github.com/xianyi/OpenBLAS/archive/v{{ version }}.tar.gz
  sha256: 5ef38b15d9c652985774869efd548b8e3e972e1e99475c673b25537ed7bcf394
  patches:
    - gh_1259.patch
    - gh_1256.patch
    - gh_1264.patch
    - gh_1279.patch
    - gh_1323.patch
    - gh_1350.patch

build:
  number: 0
  features:
    - vc14    # [win]
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain
    - perl 5.22.2.1
    - gcc              # [unix]
    - vc 14            # [win]
    - clangdev         # [win]
    - cmake            # [win]
    - ninja            # [win]
    - curl             # [win]

  run:
    - vc 14            # [win]
    - libgfortran      # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libopenblas.a                            # [unix]
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${SHLIB_EXT}']"  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\libopenblas.lib exit 1    # [win]

about:
  home: http://www.openblas.net/
  license: BSD 3-Clause
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version.

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - jschueller
    - isuruf
