{% set version = "0.3.1" %}

package:
  name: openblas
  version: {{ version }}

source:
  fn: openblas-{{ version }}.tar.gz
  url: https://github.com/xianyi/OpenBLAS/archive/v{{ version }}.tar.gz
  sha256: 1f5e956f35f3acdd3c74516e955d797a320c2e0135e31d838cbdb3ea94d0eb33

build:
  number: 1
  skip: true  # [win and vc!=14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - perl
    - cmake                      # [win]
    - curl                       # [win]
    - jom                        # [win]

  host: []

test:
  commands:
    - test -f ${PREFIX}/lib/libopenblas.a                            # [unix]
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${SHLIB_EXT}']"  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\openblas.lib exit 1    # [win]

about:
  home: http://www.openblas.net/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version.

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - jschueller
    - isuruf
