schema_version: 1

context:
  version: "0.3.33"
  build_number: 0
  string_prefix: ${{ "openmp" if USE_OPENMP == 1 else "pthreads" }}
  shlib_ext: ${{ ".so" if linux else ".dylib" if osx else ".dll" if win else "" }}

recipe:
  name: openblas-split
  version: ${{ version }}

source:
  url: https://github.com/OpenMathLib/OpenBLAS/archive/v${{ version }}.tar.gz
  sha256: 6761af1d9f5d353ab4f0b7497be2643313b36c8f31caec0144bfef198e71e6ab
  patches:
    # don't run test_fork in emulation, it has a tendency to hang indefinitely
    - if: build_platform != target_platform
      then: patches/0001-don-t-run-test_fork-in-cross-compilation.patch

build:
  number: ${{ build_number }}

outputs:
  - staging:
      name: openblas-build
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler("c") }}
        - ${{ compiler("fortran") }}
        - perl
        - if: unix
          then: make
        - if: win
          then:
            - cmake
            - ninja
        - if: osx
          then: objconv
        - if: USE_OPENMP == 1
          then: llvm-openmp
        - if: linux and USE_OPENMP == 1
          then: _openmp_mutex * *_llvm
      host:
        - if: win and USE_OPENMP == 1
          then: llvm-openmp-fortran
    build:
      script:
        file: build
        # ensure that these variants are available for the build script
        env:
          SYMBOLSUFFIX: ${{ SYMBOLSUFFIX }}
          INTERFACE64: ${{ INTERFACE64 }}

  - package:
      name: libopenblas${{ name_suffix }}
      version: ${{ version }}
    inherit: openblas-build
    build:
      string: ${{ string_prefix }}_h${{ hash }}_${{ build_number }}
      variant:
        use_keys:
          # ensure that `INTERFACE64` is included in the variant
          - INTERFACE64
        # On Windows and Linux, pthreads was the original threading model,
        # so we use it as a default by weighing down the openmp variant.
        # On macOS, OpenMP was the original threading model,
        # so we use it as a default by weighing down the pthreads variant.
        down_prioritize_variant: ${{ 1 if (not osx and USE_OPENMP == 1) or (osx and USE_OPENMP == 0) else 0 }}
      files:
        # Include files like:
        #   - libopenblasp-r0.3.5.so
        #   - libopenblas_vortexp-r0.3.5.so
        #   - libopenblas.so.0
        # Avoid files:
        #   - libopenblas.so
        - if: unix
          then:
            - lib/libopenblas${{ SYMBOLSUFFIX }}*p*${{ shlib_ext }}
        - if: linux
          then:
            - lib/libopenblas${{ SYMBOLSUFFIX }}.so.*
        - if: osx
          then:
            - lib/libopenblas${{ SYMBOLSUFFIX }}.*.dylib
        - if: win
          then:
            - Library/bin/openblas${{ SYMBOLSUFFIX }}.dll
    requirements:
      run_exports:
        - ${{ pin_subpackage("libopenblas" ~ name_suffix) }}
      # run_constraints:
        # - ${{ pin_subpackage("openblas" ~ name_suffix, upper_bound="x.x.x") }}
    tests:
      - package_contents:
          files:
            - if: unix
              then: lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}${{ shlib_ext }}
            - if: win
              then: Library/bin/openblas${{ SYMBOLSUFFIX }}.dll
      - requirements:
          run:
            - python *
        script:
          - if: osx
            then: nm -g ${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}${{ shlib_ext }} | grep dsecnd
          - if: unix
            then: python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}${{ shlib_ext }}']"

  - package:
      name: openblas${{ name_suffix }}
      version: ${{ version }}
    inherit: openblas-build
    build:
      string: ${{ string_prefix }}_h${{ hash }}_${{ build_number }}
      variant:
        # ensure that `INTERFACE64` is included in the variant
        use_keys:
          - INTERFACE64
        # On Windows and Linux, pthreads was the original threading model,
        # so we use it as a default by weighing down the openmp variant.
        # On macOS, OpenMP was the original threading model,
        # so we use it as a default by weighing down the pthreads variant.
        down_prioritize_variant: ${{ 1 if (not osx and USE_OPENMP == 1) or (osx and USE_OPENMP == 0) else 0 }}
      files:
        - if: unix
          then:
            - include/*.h
            - lib/libopenblas${{ SYMBOLSUFFIX }}.a
            - lib/libopenblas${{ SYMBOLSUFFIX }}*.a
            - lib/libopenblas${{ SYMBOLSUFFIX }}${{ shlib_ext }}
            - lib/pkgconfig/openblas.pc
            - lib/cmake/openblas/*
        - if: win
          then:
            - Library/include/openblas
            - Library/lib/openblas${{ SYMBOLSUFFIX }}.lib
            - Library/lib/pkgconfig/openblas.pc
            - Library/share/cmake/OpenBLAS
    requirements:
      run:
        - ${{ pin_subpackage("libopenblas" ~ name_suffix, exact=True) }}
    tests:
      - package_contents:
          files:
            - if: unix
              then:
                - lib/libopenblas${{ SYMBOLSUFFIX }}.a
                - lib/libopenblas${{ SYMBOLSUFFIX }}${{ shlib_ext }}
            - if: win
              then:
                - Library/lib/openblas${{ SYMBOLSUFFIX }}.lib

about:
  homepage: http://www.openblas.net/
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - lapack-netlib/LICENSE
  summary: ${{ "An optimized BLAS library (ILP64 interface) based on GotoBLAS2 1.13 BSD version" if SYMBOLSUFFIX == "64_" else "An optimized BLAS library based on GotoBLAS2 1.13 BSD version" }}
  repository: https://github.com/OpenMathLib/OpenBLAS

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - isuruf
    - h-vetinari
  feedstock-name: openblas
