schema_version: 1

context:
  version: "0.3.34"
  build_number: 1
  next_version: "0.3.35"

recipe:
  name: openblas-split
  version: ${{ version }}

source:
  url: https://github.com/OpenMathLib/OpenBLAS/archive/v${{ version }}.tar.gz
  sha256: cd7e129868320cc2d033afa920e31202dfe0b8066a5b66661900ccc0f197dfed
  patches:
    - if: build_platform != target_platform
      then: patches/0001-don-t-run-test_fork-in-cross-compilation.patch

build:
  number: ${{ build_number }}
  variant:
    use_keys:
      - INTERFACE64

outputs:
  - staging:
      name: openblas-build
    build:
      script:
        file: build
        env:
          INTERFACE64: ${{ INTERFACE64 }}
          SYMBOLSUFFIX: ${{ SYMBOLSUFFIX }}
          USE_OPENMP: ${{ USE_OPENMP }}
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('fortran') }}
        - perl
        - if: unix
          then: make
        - if: win
          then:
            - cmake
            - ninja
        - if: osx
          then: objconv
        - if: USE_OPENMP == "1"
          then: llvm-openmp
        # Following is needed because the Fortran compiler add an rpath to the BUILD_PREFIX
        - if: linux and USE_OPENMP == "1"
          then: _openmp_mutex * *_llvm
      host:
        - if: win and USE_OPENMP == "1"
          then: llvm-openmp-fortran

  - package:
      name: libopenblas
    inherit:
      from: openblas-build
      run_exports: false
    build:
      skip: INTERFACE64 != "0"
      string: ${{ "openmp" if USE_OPENMP == "1" else "pthreads" }}_h${{ hash }}_${{ build_number }}
      variant:
        down_prioritize_variant: ${{ 1 if (not osx and USE_OPENMP == "1") or (osx and USE_OPENMP == "0") else 0 }}
      files:
        - if: unix
          then: lib/libopenblas${{ SYMBOLSUFFIX }}*p*.${{ "dylib" if osx else "so" }}
        - if: linux
          then: lib/libopenblas${{ SYMBOLSUFFIX }}.so.*
        - if: osx
          then: lib/libopenblas${{ SYMBOLSUFFIX }}.*.dylib
        - if: win
          then: Library/bin/openblas${{ SYMBOLSUFFIX }}.dll
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('fortran') }}
        - if: USE_OPENMP == "1"
          then: llvm-openmp
      run_exports:
        - ${{ pin_subpackage("libopenblas") }}
      run_constraints:
        - openblas >=${{ version }},<${{ next_version }}.0a0
    tests:
      - package_contents:
          files:
            - if: linux
              then:
                - lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}.so
                - lib/libopenblas${{ SYMBOLSUFFIX }}.so.0
            - if: osx
              then:
                - lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}.dylib
                - lib/libopenblas${{ SYMBOLSUFFIX }}.0.dylib
            - if: win
              then: Library/bin/openblas${{ SYMBOLSUFFIX }}.dll
      - if: unix
        then:
          requirements:
            build:
              - binutils
          script:
            - if: osx
              then: nm -g ${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}.dylib | grep dsecnd
    about:
      homepage: http://www.openblas.net/
      repository: https://github.com/OpenMathLib/OpenBLAS
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - lapack-netlib/LICENSE
      summary: ${{ "An optimized BLAS library (ILP64 interface) based on GotoBLAS2 1.13 BSD version" if SYMBOLSUFFIX == "64_" else "An optimized BLAS library based on GotoBLAS2 1.13 BSD version" }}

  - package:
      name: libopenblas-ilp64
    inherit:
      from: openblas-build
      run_exports: false
    build:
      skip: INTERFACE64 != "1"
      string: ${{ "openmp" if USE_OPENMP == "1" else "pthreads" }}_h${{ hash }}_${{ build_number }}
      variant:
        down_prioritize_variant: ${{ 1 if (not osx and USE_OPENMP == "1") or (osx and USE_OPENMP == "0") else 0 }}
      files:
        - if: unix
          then: lib/libopenblas${{ SYMBOLSUFFIX }}*p*.${{ "dylib" if osx else "so" }}
        - if: linux
          then: lib/libopenblas${{ SYMBOLSUFFIX }}.so.*
        - if: osx
          then: lib/libopenblas${{ SYMBOLSUFFIX }}.*.dylib
        - if: win
          then: Library/bin/openblas${{ SYMBOLSUFFIX }}.dll
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('fortran') }}
        - if: USE_OPENMP == "1"
          then: llvm-openmp
      run_exports:
        - ${{ pin_subpackage("libopenblas-ilp64") }}
      run_constraints:
        - openblas-ilp64 >=${{ version }},<${{ next_version }}.0a0
    tests:
      - package_contents:
          files:
            - if: linux
              then:
                - lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}.so
                - lib/libopenblas${{ SYMBOLSUFFIX }}.so.0
            - if: osx
              then:
                - lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}.dylib
                - lib/libopenblas${{ SYMBOLSUFFIX }}.0.dylib
            - if: win
              then: Library/bin/openblas${{ SYMBOLSUFFIX }}.dll
      - if: unix
        then:
          requirements:
            build:
              - binutils
          script:
            - if: osx
              then: nm -g ${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}.dylib | grep dsecnd
    about:
      homepage: http://www.openblas.net/
      repository: https://github.com/OpenMathLib/OpenBLAS
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - lapack-netlib/LICENSE
      summary: ${{ "An optimized BLAS library (ILP64 interface) based on GotoBLAS2 1.13 BSD version" if SYMBOLSUFFIX == "64_" else "An optimized BLAS library based on GotoBLAS2 1.13 BSD version" }}

  - name: openblas
    build:
      skip: true  # [INTERFACE64 != "0"]
      string: openmp_h{{ PKG_HASH }}_{{ build_number }}  # [USE_OPENMP == 1]
      string: pthreads_h{{ PKG_HASH }}_{{ build_number }}  # [USE_OPENMP == 0]
      track_features:
        # On Windows and Linux, pthreads was the original threading model,
        # so we use it as a default by weighing down the openmp variant.
        - openblas_threading_openmp     # [(not osx) and USE_OPENMP == 1]
        # On macOS, OpenMP was the original threading model,
        # so we use it as a default by weighing down the pthreads variant.
        - openblas_threading_pthreads   # [osx and USE_OPENMP == 0]
    files:
      - include/*.h                                       # [not win]
      - lib/libopenblas{{ SYMBOLSUFFIX }}*.a              # [not win]
      - lib/libopenblas{{ SYMBOLSUFFIX }}{{ SHLIB_EXT }}  # [not win]
      - lib/pkgconfig/openblas.pc                         # [not win]
      - lib/cmake/openblas/*                              # [not win]
      - Library/include/openblas                          # [win]
      - Library/lib/openblas{{ SYMBOLSUFFIX }}.lib        # [win]
      - Library/lib/pkgconfig/openblas.pc                 # [win]
      - Library/share/cmake/OpenBLAS                      # [win]
    requirements:
      run:
        - {{ pin_subpackage("libopenblas", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libopenblas{{ SYMBOLSUFFIX }}.a                       # [not win]
        - test -f ${PREFIX}/lib/libopenblas{{ SYMBOLSUFFIX }}{{ SHLIB_EXT }}          # [not win]
        - if not exist %PREFIX%\\Library\\lib\\openblas{{ SYMBOLSUFFIX }}.lib exit 1  # [win]

  - name: openblas-ilp64
    build:
      skip: true  # [INTERFACE64 != "1"]
      string: openmp_h{{ PKG_HASH }}_{{ build_number }}  # [USE_OPENMP == 1]
      string: pthreads_h{{ PKG_HASH }}_{{ build_number }}  # [USE_OPENMP == 0]
      track_features:
        # On Windows and Linux, pthreads was the original threading model,
        # so we use it as a default by weighing down the openmp variant.
        - openblas_threading_openmp     # [(not osx) and USE_OPENMP == 1]
        # On macOS, OpenMP was the original threading model,
        # so we use it as a default by weighing down the pthreads variant.
        - openblas_threading_pthreads   # [osx and USE_OPENMP == 0]
    files:
      - include/*.h                                       # [not win]
      - lib/libopenblas{{ SYMBOLSUFFIX }}*.a              # [not win]
      - lib/libopenblas{{ SYMBOLSUFFIX }}{{ SHLIB_EXT }}  # [not win]
      - lib/pkgconfig/openblas.pc                         # [not win]
      - lib/cmake/openblas/*                              # [not win]
      - Library/include/openblas                          # [win]
      - Library/lib/openblas{{ SYMBOLSUFFIX }}.lib        # [win]
      - Library/lib/pkgconfig/openblas.pc                 # [win]
      - Library/share/cmake/OpenBLAS                      # [win]
    requirements:
      run:
        - {{ pin_subpackage("libopenblas-ilp64", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libopenblas{{ SYMBOLSUFFIX }}.a                       # [not win]
        - test -f ${PREFIX}/lib/libopenblas{{ SYMBOLSUFFIX }}{{ SHLIB_EXT }}          # [not win]
        - if not exist %PREFIX%\\Library\\lib\\openblas{{ SYMBOLSUFFIX }}.lib exit 1  # [win]

about:
  homepage: http://www.openblas.net/
  repository: https://github.com/OpenMathLib/OpenBLAS
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - lapack-netlib/LICENSE
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - isuruf
    - h-vetinari
  feedstock-name: openblas
