build_platform:
  linux_ppc64le: linux_64
provider:
  linux_aarch64: default
  osx_arm64: default
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 30
test: native_and_emulated
