appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
travis:
  secure: {BINSTAR_TOKEN: H3GgaVwc4/tgmlX4oNx6wrFlO84GmO5WnkSZrtfb2EsRUv26w52Gtr0zsMEv3fSJcheAzgBGlKcMoHNU9170LkKR20NmaxbVUzg6Cdhba4ylQhUIj9ClpMXcqCSc8bhnPY/+gLcxwlKuThUbybVMSEBfWoMp66IclFh+T5uY8uw10Ov601I0PF2qjly9DwY2nGT0kRGUM9lvr3WdWRBGYiC7oF2fFhH/zqTxBPuJnSJ5pz94NnsnfrITmdAUGlgp+Lgfpr/AKHhKv9J4xeDorc3qKG2+Xf7g/1eAH9W0jS8SxGOPTAPAQwzZezJep+Xr+vwVhnz/z8X5qNbQUUJaFHMXvPonEt4nOyeHloxiZrN8KjPb5ODyIsUdY6jCUxwZunx9qKOQeidwKPgbDhdCLYXSKL5H19PLvBQAK9ZK7h1YKlE4LEoODXhZ5qmnQkxfkGmhr4WYhiVsRSwrD3tyachIIrUKuzjNuBdq4i1gLiLPmnScPlj5xu4Lw+XNRPSdUewceC6Qr4w8dPCl5yPRAbVGegaxgxL4B1qZDG26XTDO/SL9ZNghuLH1AIZsFn4zrKsVRbdzTWoCAmmwsPLRUX5q0Z26yuJ9j0HFlM1Inl+Muxrl7m119LJCfq4irpF8jX/jd7dl9dd+Qizwp6rahXArxYOIHStze+iFgCyAppk=}
